### PR TITLE
Chart

### PR DESCRIPTION
**Pull request by Dwina83**
Downloaded chart.js so it's available even offline, add chart controller integration test and more css :)
I don't why one of the checks is failed tho, but I can run the app without any error and the database is perfectly fine. When I run the test in VS everything is passed. 
15 minutes later:
Ok I've checked it, it's one of the OpenAI test that failed.

### CODE REVIEW

**Review by Rasmus-2 — COMMENTED** [review]
I've looked through all the files and it looks good to me, can't find any reason in the code why the test would fail now.

**Comment by matakesson** [comment]
Seems "  Failed SportsGoalAppTests.ChartControllerIntegrationTest.GetChartValue_ReturnOk_WithValue [17 s] " is the problem, no? Or am I missing something

**Comment by Dwina83** [comment]
Screenshot 2024-12-05 144524

we have 18 tests in total in this one is failed. Strange it was fine yesterday, right?

**Comment by matakesson** [comment]
> Screenshot 2024-12-05 144524
> 
> we have 18 tests in total in this one is failed. Strange it was fine yesterday, right?

Do you have the API-Key in visual studio? Otherwise that will probably fail for you locally. But you said it worked yesterday?

**Comment by Dwina83** [comment]
> Seems " Failed SportsGoalAppTests.ChartControllerIntegrationTest.GetChartValue_ReturnOk_WithValue [17 s] " is the problem, no? Or am I missing something

I guess you right, i found this 
Screenshot 2024-12-05 144944
but it passed in VS, how come?

**Comment by Dwina83** [comment]
> > Screenshot 2024-12-05 144524
> > we have 18 tests in total in this one is failed. Strange it was fine yesterday, right?
> 
> Do you have the API-Key in visual studio? Otherwise that will probably fail for you locally. But you said it worked yesterday?

hahaha i guess that's why. But still doesn't explain why my SQL is failing, gives error on the checks test but passed on VS test...

**Comment by matakesson** [comment]
Would guess that your CI test here failed due to not having a Database reference. When you run it in VS it will use your local SQLExpress but that won't work outside your computer. 

GetChartData_ShouldReturnPercentageData() probably works because you are mocking a database in the test, where as GetChartValue_ReturnOk_WithValue() ask for data from a real db that doesn't exist outside your computer.

**Pull request merged**
